In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/githubactivities/userdata.npz
/kaggle/input/githubactivities/tmp.mm
/kaggle/input/githubactivities/scalers.pkl.z
/kaggle/input/githubactivities/ml.npz
/kaggle/input/notebook13088a6bed/model.pth
/kaggle/input/notebook13088a6bed/epoch=27-val_loss=2.538.ckpt
/kaggle/input/notebook13088a6bed/epoch=17-val_loss=2.533.ckpt
/kaggle/input/notebook13088a6bed/epoch=18-val_loss=2.527.ckpt
/kaggle/input/notebook13088a6bed/__results__.html
/kaggle/input/notebook13088a6bed/epoch=19-val_loss=2.527.ckpt
/kaggle/input/notebook13088a6bed/epoch=24-val_loss=2.536.ckpt
/kaggle/input/notebook13088a6bed/epoch=21-val_loss=2.528.ckpt
/kaggle/input/notebook13088a6bed/epoch=23-val_loss=2.530.ckpt
/kaggle/input/notebook13088a6bed/epoch=22-val_loss=2.534.ckpt
/kaggle/input/notebook13088a6bed/last.ckpt
/kaggle/input/notebook13088a6bed/__notebook__.ipynb
/kaggle/input/notebook13088a6bed/epoch=16-val_loss=2.532.ckpt
/kaggle/input/notebook13088a6bed/__output__.json
/kaggle/input/notebook13088a6bed/epoch=2

In [2]:
def has_cuda():
    """check cuda without having to import pytorch into the current process"""
    import os
    res = os.system('python -c "import torch; import sys; sys.exit(14 if torch.cuda.is_available() else 7)"')
    return ((res >> 8) & (255)) == 14

In [3]:
import math
import time
import torch
import random
from torch import Tensor
from torch import nn
from torch.optim.lr_scheduler import ReduceLROnPlateau, CyclicLR
from torch.nn import functional as F
from pathlib import Path

torch.set_num_threads(os.cpu_count())
from torch.utils.data import Dataset, DataLoader

In [4]:
class GithubContribDataset(Dataset):
    def __init__(self, base_path='.', seq_size=64):
        self.base_path = Path(base_path)
        self.seq_size = seq_size
        self._len = 0
        self.data = dict()
        self.weeks = None
        self.weeks_cluster = None
        self.scaled_weeks = None
        self.weeks_target = None
        self.users = None
        
    def load(self):
        self.data = np.load(self.base_path / 'ml.npz')
        scaled_weeks = self.scaled_weeks = self.data['scaled_weeks']
        self.users = self.data['users'].astype('float32')
        self.weeks = self.data['weeks'].astype('float32')
        self.weeks_cluster = self.data['weeks_cluster'].astype('int32')
        self._len = len(scaled_weeks) * (scaled_weeks.shape[1] - self.seq_size - 7)
        
        self.weeks_target = np.concatenate((self.weeks[:, :, None], self.weeks_cluster[:, :, None]), axis=2).astype('float32')
        
    def __len__(self):
        return self._len

    
    def __getitem__(self, key):
        weeks = self.weeks
        idx = key // (weeks.shape[1] - self.seq_size - 7)
        idx2 = key % (weeks.shape[1] - self.seq_size - 7)
        users = self.users
        return (
            torch.tensor([idx2 % 7]),
            torch.from_numpy(users[idx]),
            torch.from_numpy(self.scaled_weeks[idx, idx2:idx2 + self.seq_size]),
            torch.from_numpy(self.weeks_target[idx, idx2 + self.seq_size:idx2 + self.seq_size + 7])
        )

In [5]:
ds = GithubContribDataset("/kaggle/input/githubactivities")
ds.load()
len(ds)

1543464

In [6]:
%%time
for i in range(len(ds)):
    ds[i]

CPU times: user 10.3 s, sys: 37.4 ms, total: 10.3 s
Wall time: 10.3 s


In [7]:
ds[random.randint(0, len(ds))]

(tensor([0]),
 tensor([ 0.9689,  0.6029, -0.0257,  1.6440,  1.0653,  0.8073,  0.3753,  1.5639,
         -0.0647,  0.4729, -1.6652, -1.0387,  1.2578, -0.7865, -0.7814,  0.3366,
          0.0211,  0.0659,  0.1640,  0.0056, -0.0178,  0.2993,  0.0529, -0.1946,
          0.3055,  0.0559, -0.1523,  0.9457,  0.3076, -0.5332,  0.9000,  1.0842,
          1.0611, -0.4067, -0.2662,  0.6719,  0.0102, -0.0512,  0.1173,  0.4493,
         -0.3669, -0.6189,  0.3790,  0.4520,  1.5668, -0.5365, -0.0449, -0.4106,
         -0.3345,  0.4356,  1.1104,  0.4354, -0.2439,  1.4704, -0.5826, -0.0104,
          0.6715,  0.2240,  0.0107, -0.5874]),
 tensor([0.0000, 0.0000, 0.9243, 0.0000, 0.0000, 0.9243, 0.0000, 0.0000, 0.0000,
         0.0000, 0.9243, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9243,
         0.0000, 0.0000, 0.9243, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.9243,
         0.0000, 0.9243, 0.0000, 0.0000, 0.0000, 0.9243, 0.0000, 0.0000, 0.9243,
         0.0000, 0.0000, 0.9243, 0.0000, 0.0000,

In [8]:
import pytorch_lightning as pl

In [9]:
class GCModel(nn.Module):
    def __init__(self, seq_size: int, user_features: int):
        super().__init__()
        hidden_size = 256
        
        self.contrib_w = nn.Parameter(torch.empty((seq_size, user_features, 8), dtype=torch.cfloat))
        torch.nn.init.kaiming_normal_(self.contrib_w)
        
        self.contrib_b = nn.Parameter(torch.empty((7, seq_size, user_features, 8), dtype=torch.cfloat))
        torch.nn.init.xavier_uniform_(self.contrib_b, 0.5)
        
        self.contrib_alpha = nn.Parameter(torch.empty((1, 1, user_features), dtype=torch.cfloat))
        torch.nn.init.kaiming_normal_(self.contrib_alpha)
        
        self.hidden_alpha = nn.Parameter(torch.empty((7, user_features), dtype=torch.cfloat))
        torch.nn.init.kaiming_normal_(self.hidden_alpha)
        
        self.user_bn = nn.BatchNorm1d(user_features)
        
        self.hidden = nn.Sequential(
            nn.Conv1d(user_features, hidden_size, 1),
            nn.Mish(inplace=True),
            nn.Conv1d(hidden_size, hidden_size, 7, 7),
            nn.GroupNorm(8, hidden_size),
            nn.Mish(inplace=True),
            nn.Conv1d(hidden_size, user_features, 3)
        )
        
        self.final = nn.Sequential(
            nn.BatchNorm1d(7 * user_features),
            nn.Linear(7 * user_features, hidden_size),
            nn.Mish(inplace=True),
            nn.Dropout(0.2),
            nn.Linear(hidden_size, 7 * 6 * 2, bias=True)
        )
        
    def forward(self, day: Tensor, users: Tensor, contribs: Tensor):
        contrib_b = self.contrib_b[None, :, :, :, :].expand(day.size(0), -1, -1, -1, -1)
        contrib_b = torch.gather(contrib_b, 1, day[:, :, None, None, None].expand(-1, 1, *contrib_b.size()[2:]))
        
        if self.training:
            contrib_mask = torch.rand_like(contribs) > torch.randint(0, 5, (contribs.size(0), 1), device=contribs.device, dtype=contribs.dtype) / 100
            contribs_std, contribs_mean = torch.std_mean(contribs)
            contribs_std2, contribs_mean2 = torch.std_mean(contribs, dim=1, keepdim=True)
            
            contribs_std = torch.where(
                torch.randint_like(contribs, 0, 3) == 0,
                contribs_std,
                contribs_std2
            )
            contribs_mean = torch.where(
                torch.randint_like(contribs, 0, 3) == 0,
                contribs_mean,
                contribs_mean2
            )
            
            noise = torch.normal(contribs_mean, contribs_std).to(device=contribs.device)
            mult = torch.randint_like(noise, 0, 101).float() / 100
            contribs = torch.where(
                torch.randint_like(contribs, 0, 11) > 9,
                (1 - mult) * contribs + noise * mult,
                contribs + (noise - contribs_mean) * torch.randint_like(noise, 0, 5).float() / 100
            )
            contribs = contribs * contrib_mask
            contribs = contribs.relu()
        
        contribs_x = torch.fft.fft(contribs[:, :, None, None], dim=1, norm='ortho') * self.contrib_w + contrib_b.squeeze_(1)
        
        users = self.user_bn(users)
        if self.training:
            noise = torch.randn_like(users)
            users_std = torch.std(users, dim=0, keepdim=True).expand_as(users)
            noise = torch.normal(0, users_std).to(device=users.device)
            users = users + noise.detach() * torch.randint_like(noise, 0, 5) / 100
        contribs_x = torch.fft.fft(users, dim=1, norm='ortho')[:, None, :, None].expand_as(contribs_x) * torch.fft.fft(contribs_x, dim=3)
        contribs_x = torch.fft.ifft(contribs_x, dim=3)
        contrib_alpha = torch.sigmoid(self.contrib_alpha)
        contribs_x = contrib_alpha * torch.amax(torch.abs(contribs_x), dim=3) + (1 - contrib_alpha) * torch.mean(contribs_x, dim=3)
        acontribs_x = torch.abs(contribs_x)
        contribs_x = contribs_x * (acontribs_x > torch.quantile(acontribs_x, 0.1, dim=2, keepdim=True))
        contribs_x = torch.fft.ifft2(contribs_x, dim=(1, 2), norm='ortho')
        hidden = self.hidden(contribs_x.real.permute(0, 2, 1)).permute(0, 2, 1)
        hidden_alpha = self.hidden_alpha.tanh()
        hidden = torch.fft.fft2(hidden, dim=(2, 1)) * hidden_alpha + torch.fft.fft(contribs_x[:, -hidden.size(1):, :], dim=1) * (1 - hidden_alpha)
        ahidden = torch.abs(hidden)
        hidden = hidden * (ahidden > torch.quantile(ahidden, 0.1, dim=1, keepdim=True)) # mimic fft filters
        hidden = torch.fft.ifft(hidden, dim=1)
        res = self.final(hidden.real.reshape(hidden.size(0), -1)).view(hidden.size(0), 6, 7, 2)
        return res

In [10]:
model = GCModel(ds.seq_size, ds.users.shape[-1])
display(model)
model.eval()(*(x[None, :] for x in ds[800][:-1]))

GCModel(
  (user_bn): BatchNorm1d(60, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (hidden): Sequential(
    (0): Conv1d(60, 256, kernel_size=(1,), stride=(1,))
    (1): Mish(inplace=True)
    (2): Conv1d(256, 256, kernel_size=(7,), stride=(7,))
    (3): GroupNorm(8, 256, eps=1e-05, affine=True)
    (4): Mish(inplace=True)
    (5): Conv1d(256, 60, kernel_size=(3,), stride=(1,))
  )
  (final): Sequential(
    (0): BatchNorm1d(420, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): Linear(in_features=420, out_features=256, bias=True)
    (2): Mish(inplace=True)
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=256, out_features=84, bias=True)
  )
)

tensor([[[[-8.8224e-02, -3.7022e-02],
          [-5.0656e-02,  9.3514e-02],
          [ 8.7698e-02,  6.5676e-02],
          [ 7.8713e-02,  3.3581e-02],
          [ 2.2424e-03, -2.5395e-02],
          [ 3.2551e-02,  9.7452e-02],
          [-2.8054e-02, -1.1142e-01]],

         [[ 6.3080e-02, -8.7416e-03],
          [-4.3996e-02, -1.7438e-02],
          [-8.8441e-02, -9.3863e-03],
          [ 5.8212e-03, -2.8414e-02],
          [ 5.1421e-02, -4.1356e-02],
          [-7.0226e-03,  1.2616e-01],
          [-4.5512e-02, -6.5531e-02]],

         [[-6.2744e-02,  3.5022e-02],
          [ 5.5764e-02,  2.8445e-02],
          [ 1.1783e-01,  3.2825e-02],
          [-1.1133e-01,  9.2630e-02],
          [-2.4136e-03, -5.2065e-02],
          [ 3.7178e-05,  5.3216e-02],
          [ 3.6583e-02, -6.4883e-02]],

         [[-1.4602e-02,  8.6457e-03],
          [-1.0520e-01,  8.5515e-02],
          [ 1.6303e-02, -9.6017e-02],
          [-5.8602e-02,  5.9570e-02],
          [ 1.5500e-02, -5.3753e-02],
      

In [11]:
weight = np.sum(ds.data['value_counts']) / ds.data['value_counts']
weight /= np.min(weight)
weight

array([  1.        ,  22.04706175,  28.47726225,  74.42100843,
       105.27409359, 192.04041832])

In [12]:
class CLoss(nn.Module):
    def __init__(self, weight):
        super().__init__()
        weight=torch.tensor(weight).float()
        self.register_buffer('rescale_weight', weight)
        self.ce = nn.CrossEntropyLoss(weight, reduction='none')
        self.regr = nn.SmoothL1Loss(reduction='none')
        seq_weight = 1 / (torch.arange(7) + 1)[None, :]
        self.register_buffer('seq_weight', seq_weight)
        
    def forward(self, preds, y_true):
        ce = self.ce(preds[:, :, :, 1], y_true[:, :, 1].long())
        x = torch.gather(preds[:, :, :, 0], 1, y_true[:, None, :, 1].long())
        regr = self.regr(x.squeeze(1), y_true[:, :, 0])
        regr_full = self.regr(preds[:, :, :, 0], y_true[:, None, :, 0]) * preds[:, :, :, 1].softmax(1)
        rescale_weight = torch.gather(self.rescale_weight[None, :, None].expand(y_true.size(0), -1, y_true.size(1)), 1, y_true[:, None, :, 1].long())
        return ((regr +
                 regr_full.sum(1) * rescale_weight.squeeze(1) / torch.amax(self.rescale_weight) +
                 ce) * self.seq_weight).mean()

In [13]:
# use 20% of training data for validation
train_set_size = int(len(ds) * 0.8)
valid_set_size = len(ds) - train_set_size

# split the train set into two
seed = torch.Generator().manual_seed(42)
train_set, valid_set = torch.utils.data.random_split(ds, [train_set_size, valid_set_size], generator=seed)

In [14]:
class GCLightningModule(pl.LightningModule):
    def __init__(self, model):
        super().__init__()
        self.model = model
        self.loss_model = CLoss(weight=weight)
        self.eval_loss_model = CLoss(weight=weight).eval()
        self.batch_size = getattr(self, 'batch_size', 0) or 64
        self.lr = getattr(self, 'lr', 0) or 1e-3
        self.save_hyperparameters(ignore=['model'])

    def training_step(self, batch, batch_idx):
        day, users, contribs, target = batch
        y = self.model(day, users, contribs)
        loss = self.loss_model(y, target)
        self.log("train_loss", loss)
        return loss
    
    def validation_step(self, batch, batch_idx):
        # this is the validation loop
        day, users, contribs, target = batch
        y = self.model(day, users, contribs)
        test_loss = self.eval_loss_model(y, target)
        self.log("val_loss", test_loss)
        
    def predict_step(self, batch, batch_idx, dataloader_idx=0):
        return self.model(batch)
    
    def train_dataloader(self):
        return torch.utils.data.DataLoader(train_set, batch_size=self.batch_size or self.hparams.batch_size, shuffle=True)
    
    def val_dataloader(self):
        return torch.utils.data.DataLoader(valid_set, batch_size=512)

    def configure_optimizers(self):
        optimizer = torch.optim.AdamW(self.parameters(), lr=self.lr or self.learning_rate)
        return optimizer
    
gc_module = GCLightningModule(model)

In [15]:
train_loader = torch.utils.data.DataLoader(ds, 8, shuffle=True)
len(train_loader)

192933

In [16]:
from pytorch_lightning.callbacks import StochasticWeightAveraging, EarlyStopping, ModelCheckpoint

class MyStochasticWeightAveraging(StochasticWeightAveraging):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._average_model = getattr(self, '_average_model', None)

In [17]:
trainer = pl.Trainer(limit_train_batches=10000, max_epochs=50, deterministic=False, max_time="00:11:00:00", callbacks=[
    #MyStochasticWeightAveraging(swa_lrs=1e-5, swa_epoch_start=0.5, annealing_epochs=5),
    EarlyStopping(monitor="val_loss", mode="min", patience=10, verbose=True, check_finite=True, strict=True),
    ModelCheckpoint(".", monitor="val_loss", verbose=True, filename='{epoch}-{val_loss:.3f}', save_last=True, save_top_k=10)
], auto_lr_find=False, accumulate_grad_batches={0: 1, 1: 1, 4: 2, 6: 4, 8: 16, 16:32}, gradient_clip_val=5.0,
                    devices="auto", accelerator="auto")
#trainer.tune(gc_module)
trainer.fit(model=gc_module)

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:616: UserWarning: Checkpoint directory /kaggle/working exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")


Sanity Checking: 0it [00:00, ?it/s]

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/loss.py:921: UserWarning: Using a target size (torch.Size([512, 1, 7])) that is different to the input size (torch.Size([512, 6, 7])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta)


Training: 0it [00:00, ?it/s]

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/loss.py:921: UserWarning: Using a target size (torch.Size([64, 1, 7])) that is different to the input size (torch.Size([64, 6, 7])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta)
/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py:175: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at  /usr/local/src/pytorch/aten/src/ATen/native/Copy.cpp:239.)
  allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass


Validation: 0it [00:00, ?it/s]

/opt/conda/lib/python3.7/site-packages/torch/nn/modules/loss.py:921: UserWarning: Using a target size (torch.Size([469, 1, 7])) that is different to the input size (torch.Size([469, 6, 7])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta)


Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

Validation: 0it [00:00, ?it/s]

In [18]:
data = ds[random.randint(0, len(ds))]
with torch.no_grad():
    result = model.cpu().eval()(*(x[None, :] for x in data[:-1]))
    am = result[:,:,:,1].argmax(1, keepdims=True)
    contribs = torch.gather(result[:,:,:,0], 1, am)
    print(am, contribs.numpy(), data[-1].numpy())

tensor([[[0, 0, 0, 0, 0, 0, 0]]]) [[[ 6.5044523e-03  2.2161296e-03  2.4959575e-03  6.9860225e-03
   -4.4504646e-05  3.4776917e-03  2.4622798e-03]]] [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [19]:
torch.save(model.state_dict(), 'model.pth')